export enum ProfileStatus {
  CREATED = 'CREATED',
  IN_PROGRESS = 'IN_PROGRESS',
  PARTIALLY_COMPLETED = 'PARTIALLY_COMPLETED',
  COMPLETED = 'COMPLETED',
  VERIFIED = 'VERIFIED',
  ARCHIVED = 'ARCHIVED',
}

export enum VerificationStatus {
  UNVERIFIED = 'UNVERIFIED',
  SELF_DECLARED = 'SELF_DECLARED',
  SYSTEM_VERIFIED = 'SYSTEM_VERIFIED',
  DOCUMENT_VERIFIED = 'DOCUMENT_VERIFIED',
  REJECTED = 'REJECTED',
}

export enum CreationMethod {
  USER_FORM = 'USER_FORM',
  OCR = 'OCR',
  ADMIN = 'ADMIN',
  DIGILOCKER = 'DIGILOCKER',
  API = 'API',
  IMPORT = 'IMPORT',
  AI_EXTRACTION = 'AI_EXTRACTION',
}

export enum ConfidenceSource {
  USER = 'USER',
  DOCUMENT = 'DOCUMENT',
  AI = 'AI',
  ADMIN = 'ADMIN',
  SYSTEM = 'SYSTEM',
}

export enum FactSourcePrecedence {
  GOVERNMENT_VERIFIED = 1,
  MANUAL_OFFICER_VERIFIED = 2,
  DOCUMENT_DERIVED = 3,
  SYSTEM_DERIVED = 4,
  SELF_DECLARED = 5,
}

export enum FactFreshnessStatus {
  FRESH = 'FRESH',
  EXPIRING_SOON = 'EXPIRING_SOON',
  STALE = 'STALE',
  UNKNOWN = 'UNKNOWN',
}

export enum PrioritizationTieBreakerReason {
  HIGHER_ELIGIBILITY_RELEVANCE = 'HIGHER_ELIGIBILITY_RELEVANCE',
  HIGHER_DOWNSTREAM_IMPACT = 'HIGHER_DOWNSTREAM_IMPACT',
  HIGHER_RECOMMENDATION_UNLOCK = 'HIGHER_RECOMMENDATION_UNLOCK',
  LOWER_CITIZEN_EFFORT = 'LOWER_CITIZEN_EFFORT',
  STABLE_QUESTION_VERSION_ID = 'STABLE_QUESTION_VERSION_ID',
}
