export enum DocumentStatus {
  UPLOADED = 'UPLOADED',
  STORED = 'STORED',
  CLASSIFIED = 'CLASSIFIED',
  QUALITY_CHECKED = 'QUALITY_CHECKED',
  OCR_PROCESSED = 'OCR_PROCESSED',
  FACTS_EXTRACTED = 'FACTS_EXTRACTED',
  VERIFICATION_PENDING = 'VERIFICATION_PENDING',
  VERIFIED = 'VERIFIED',
  ACTIVE = 'ACTIVE',
  SUPERSEDED = 'SUPERSEDED',
  ARCHIVED = 'ARCHIVED',
}

export enum DocumentType {
  IDENTITY_PROOF = 'IDENTITY_PROOF',
  INCOME_CERTIFICATE = 'INCOME_CERTIFICATE',
  LAND_RECORD = 'LAND_RECORD',
  CASTE_CERTIFICATE = 'CASTE_CERTIFICATE',
  BANK_PASSBOOK = 'BANK_PASSBOOK',
  RESIDENCE_PROOF = 'RESIDENCE_PROOF',
  DISABILITY_CERTIFICATE = 'DISABILITY_CERTIFICATE',
  OTHER = 'OTHER',
}

export enum DocumentQualityGrade {
  EXCELLENT = 'EXCELLENT',
  GOOD = 'GOOD',
  FAIR = 'FAIR',
  POOR = 'POOR',
  UNUSABLE = 'UNUSABLE',
}

export enum OCRReadiness {
  READY = 'READY',
  NEEDS_PREPROCESSING = 'NEEDS_PREPROCESSING',
  UNUSABLE = 'UNUSABLE',
  SKIPPED = 'SKIPPED',
}

export enum EvidenceStatus {
  UNVERIFIED = 'UNVERIFIED',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
  SUPERSEDED = 'SUPERSEDED',
}

export enum DocumentVerificationStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
  REQUIRES_MANUAL_REVIEW = 'REQUIRES_MANUAL_REVIEW',
}

export enum ConflictStatus {
  DETECTED = 'DETECTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  RESOLVED = 'RESOLVED',
  IGNORED = 'IGNORED',
}

export enum DocumentConfidenceLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  VERY_HIGH = 'VERY_HIGH',
  CRITICAL = 'CRITICAL',
}

export enum VerificationMethod {
  CITIZEN_UPLOAD = 'CITIZEN_UPLOAD',
  GOVERNMENT_API = 'GOVERNMENT_API',
  DIGILOCKER = 'DIGILOCKER',
  MANUAL_OFFICER = 'MANUAL_OFFICER',
  OCR_AUTOMATED = 'OCR_AUTOMATED',
}

export enum DocumentSource {
  CITIZEN_UPLOAD = 'CITIZEN_UPLOAD',
  DIGILOCKER = 'DIGILOCKER',
  GOVERNMENT_PORTAL = 'GOVERNMENT_PORTAL',
  OFFICER_UPLOAD = 'OFFICER_UPLOAD',
}

export enum OCRStatus {
  QUEUED = 'QUEUED',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  SKIPPED = 'SKIPPED',
}

export enum ConflictResolutionType {
  ACCEPT_DOCUMENT = 'ACCEPT_DOCUMENT',
  ACCEPT_CITIZEN_DECLARATION = 'ACCEPT_CITIZEN_DECLARATION',
  MANUAL_OVERRIDE = 'MANUAL_OVERRIDE',
  SUPERSEDE = 'SUPERSEDE',
}
