export enum EligibilityStatus {
  ELIGIBLE = 'ELIGIBLE',
  INELIGIBLE = 'INELIGIBLE',
  POTENTIALLY_ELIGIBLE = 'POTENTIALLY_ELIGIBLE',
  REQUIRES_MORE_DATA = 'REQUIRES_MORE_DATA',
  EXPIRED = 'EXPIRED',
}

export enum RuleOperator {
  EQUALS = 'EQUALS',
  NOT_EQUALS = 'NOT_EQUALS',
  GREATER_THAN = 'GREATER_THAN',
  LESS_THAN = 'LESS_THAN',
  GREATER_OR_EQUAL = 'GREATER_OR_EQUAL',
  LESS_OR_EQUAL = 'LESS_OR_EQUAL',
  BETWEEN = 'BETWEEN',
  IN = 'IN',
  NOT_IN = 'NOT_IN',
  EXISTS = 'EXISTS',
  NOT_EXISTS = 'NOT_EXISTS',
  REGEX = 'REGEX',
  BOOLEAN = 'BOOLEAN',
}

export enum LogicalGroupOperator {
  ALL = 'ALL',
  ANY = 'ANY',
  NONE = 'NONE',
  X_OF_Y = 'X_OF_Y',
}

export enum RuleEvaluationCost {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
}

export enum RuleDependencyType {
  DEPENDS_ON = 'DEPENDS_ON',
  BLOCKS = 'BLOCKS',
  REQUIRES = 'REQUIRES',
  OPTIONAL = 'OPTIONAL',
}

export enum OpportunityGapType {
  INCOME_THRESHOLD_EXCEEDED = 'INCOME_THRESHOLD_EXCEEDED',
  AGE_THRESHOLD_NOT_MET = 'AGE_THRESHOLD_NOT_MET',
  MISSING_IDENTIFIER = 'MISSING_IDENTIFIER',
  MISSING_EVIDENCE = 'MISSING_EVIDENCE',
  LOCATION_MISMATCH = 'LOCATION_MISMATCH',
}
