export enum FactConflictCategory {
  VALUE_MISMATCH = 'VALUE_MISMATCH',
  DATE_MISMATCH = 'DATE_MISMATCH',
  SOURCE_CONFLICT = 'SOURCE_CONFLICT',
  EXPIRED_EVIDENCE = 'EXPIRED_EVIDENCE',
  LOW_TRUST_EVIDENCE = 'LOW_TRUST_EVIDENCE',
  DUPLICATE_FACT = 'DUPLICATE_FACT',
  INCOMPLETE_EVIDENCE = 'INCOMPLETE_EVIDENCE',
  VERIFICATION_CONFLICT = 'VERIFICATION_CONFLICT',
}

export enum ConflictSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum ReconciliationStatus {
  DETECTED = 'DETECTED',
  CLASSIFIED = 'CLASSIFIED',
  EVIDENCE_VALIDATED = 'EVIDENCE_VALIDATED',
  POLICY_EVALUATED = 'POLICY_EVALUATED',
  RESOLUTION_SELECTED = 'RESOLUTION_SELECTED',
  CANONICAL_FACT_UPDATED = 'CANONICAL_FACT_UPDATED',
  IMPACT_CALCULATED = 'IMPACT_CALCULATED',
  SNAPSHOT_CREATED = 'SNAPSHOT_CREATED',
  EVENT_OUTBOX_COMMITTED = 'EVENT_OUTBOX_COMMITTED',
}

export enum ReconciliationStrategy {
  ACCEPT_GOVERNMENT = 'ACCEPT_GOVERNMENT',
  ACCEPT_OFFICER = 'ACCEPT_OFFICER',
  ACCEPT_DOCUMENT = 'ACCEPT_DOCUMENT',
  ACCEPT_SYSTEM = 'ACCEPT_SYSTEM',
  ACCEPT_CITIZEN = 'ACCEPT_CITIZEN',
  MERGE = 'MERGE',
  REQUIRE_MANUAL_REVIEW = 'REQUIRE_MANUAL_REVIEW',
  DEFER = 'DEFER',
}

export enum ManualReviewStatus {
  PENDING = 'PENDING',
  ASSIGNED = 'ASSIGNED',
  IN_REVIEW = 'IN_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  ESCALATED = 'ESCALATED',
}
