export enum ApplicationJourneyStatus {
  CREATED = 'CREATED',
  PLANNED = 'PLANNED',
  READY = 'READY',
  IN_PROGRESS = 'IN_PROGRESS',
  WAITING_FOR_DOCUMENTS = 'WAITING_FOR_DOCUMENTS',
  WAITING_FOR_VERIFICATION = 'WAITING_FOR_VERIFICATION',
  READY_TO_SUBMIT = 'READY_TO_SUBMIT',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  ADDITIONAL_INFORMATION_REQUIRED = 'ADDITIONAL_INFORMATION_REQUIRED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  BENEFIT_RECEIVED = 'BENEFIT_RECEIVED',
  CLOSED = 'CLOSED',
  ARCHIVED = 'ARCHIVED',
}

export enum JourneyStepStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  BLOCKED = 'BLOCKED',
  READY = 'READY',
  COMPLETED = 'COMPLETED',
  SKIPPED = 'SKIPPED',
}

export enum ChecklistStatus {
  PENDING = 'PENDING',
  PARTIALLY_MET = 'PARTIALLY_MET',
  COMPLETED = 'COMPLETED',
  EXPIRED = 'EXPIRED',
}

export enum DocumentRequirementStatus {
  REQUIRED = 'REQUIRED',
  PROVIDED = 'PROVIDED',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
}

export enum JourneyUrgency {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum TimelineEventType {
  RECOMMENDATION_GENERATED = 'RECOMMENDATION_GENERATED',
  JOURNEY_CREATED = 'JOURNEY_CREATED',
  CHECKLIST_GENERATED = 'CHECKLIST_GENERATED',
  DOCUMENT_ADDED = 'DOCUMENT_ADDED',
  VERIFICATION_COMPLETE = 'VERIFICATION_COMPLETE',
  APPLICATION_SUBMITTED = 'APPLICATION_SUBMITTED',
  STATUS_UPDATED = 'STATUS_UPDATED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum JourneyDependencyType {
  REQUIRES = 'REQUIRES',
  BLOCKS = 'BLOCKS',
  OPTIONAL = 'OPTIONAL',
  PARALLEL = 'PARALLEL',
}

export enum JourneyProgressType {
  OVERALL = 'OVERALL',
  CATEGORY = 'CATEGORY',
  STEP = 'STEP',
  DEPENDENCY = 'DEPENDENCY',
  DOCUMENT = 'DOCUMENT',
  VERIFICATION = 'VERIFICATION',
}

export enum StepExecutionMode {
  MANUAL = 'MANUAL',
  AUTOMATIC = 'AUTOMATIC',
}

export enum StepOwner {
  CITIZEN = 'CITIZEN',
  GOVERNMENT_OFFICER = 'GOVERNMENT_OFFICER',
  EXTERNAL_AGENCY = 'EXTERNAL_AGENCY',
}

export enum StepBlockingBehavior {
  BLOCKING = 'BLOCKING',
  NON_BLOCKING = 'NON_BLOCKING',
  WARNING_ONLY = 'WARNING_ONLY',
}
