export enum PolicyLifecycleStatus {
  DISCOVERED = 'DISCOVERED',
  DOWNLOADED = 'DOWNLOADED',
  PROCESSED = 'PROCESSED',
  NORMALIZED = 'NORMALIZED',
  ACTIVE = 'ACTIVE',
  SUPERSEDED = 'SUPERSEDED',
  ARCHIVED = 'ARCHIVED',
}

export enum KnowledgeSourceType {
  PORTAL = 'PORTAL',
  GAZETTE = 'GAZETTE',
  API = 'API',
  BUDGET = 'BUDGET',
  SCHOLARSHIP = 'SCHOLARSHIP',
  GAZETTE_PDF = 'GAZETTE_PDF',
}

export enum CrawlStrategy {
  REALTIME_POLL = 'REALTIME_POLL',
  CRON_SCHEDULE = 'CRON_SCHEDULE',
  WEB_SCRAPE = 'WEB_SCRAPE',
  MANUAL_UPLOAD = 'MANUAL_UPLOAD',
  API_PULL = 'API_PULL',
}

export enum PolicyRelationshipType {
  SUPERSEDES = 'SUPERSEDES',
  DEPENDS_ON = 'DEPENDS_ON',
  EXTENDS = 'EXTENDS',
  RELATED_SCHEME = 'RELATED_SCHEME',
  REQUIRED_DOCUMENT = 'REQUIRED_DOCUMENT',
  PARENT_POLICY = 'PARENT_POLICY',
  CHILD_POLICY = 'CHILD_POLICY',
}

export enum DocumentClassification {
  SCHEME = 'SCHEME',
  GOVERNMENT_ORDER = 'GOVERNMENT_ORDER',
  GAZETTE = 'GAZETTE',
  CIRCULAR = 'CIRCULAR',
  NOTIFICATION = 'NOTIFICATION',
  AMENDMENT = 'AMENDMENT',
  GUIDELINE = 'GUIDELINE',
  FAQ = 'FAQ',
  BUDGET = 'BUDGET',
  PRESS_RELEASE = 'PRESS_RELEASE',
}

export enum EmbeddingStatus {
  PENDING = 'PENDING',
  GENERATED = 'GENERATED',
  FAILED = 'FAILED',
}
