export enum NotificationStatus {
  CREATED = 'CREATED',
  RENDERED = 'RENDERED',
  QUEUED = 'QUEUED',
  PARTIALLY_DELIVERED = 'PARTIALLY_DELIVERED',
  DELIVERED = 'DELIVERED',
  READ = 'READ',
  FAILED = 'FAILED',
  SUPPRESSED = 'SUPPRESSED',
  SUPERSEDED = 'SUPERSEDED',
  EXPIRED = 'EXPIRED',
}

export enum DeliveryStatus {
  PENDING = 'PENDING',
  LEASED = 'LEASED',
  PROCESSING = 'PROCESSING',
  SUCCEEDED = 'SUCCEEDED',
  RETRY_SCHEDULED = 'RETRY_SCHEDULED',
  PERMANENT_FAILURE = 'PERMANENT_FAILURE',
  CANCELLED = 'CANCELLED',
}

export enum DeliveryAttemptStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  SUCCEEDED = 'SUCCEEDED',
  FAILED = 'FAILED',
  RETRY_SCHEDULED = 'RETRY_SCHEDULED',
  DEAD_LETTERED = 'DEAD_LETTERED',
  CANCELLED = 'CANCELLED',
}

export enum ActionItemStatus {
  PENDING = 'PENDING',
  VIEWED = 'VIEWED',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  ACTION_REQUIRED = 'ACTION_REQUIRED',
  COMPLETED = 'COMPLETED',
  DISMISSAL_REQUESTED = 'DISMISSAL_REQUESTED',
  DISMISSED = 'DISMISSED',
  EXPIRED = 'EXPIRED',
  SUPERSEDED = 'SUPERSEDED',
}

export enum NotificationPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum NotificationChannel {
  IN_APP = 'IN_APP',
  EMAIL = 'EMAIL',
  SMS = 'SMS',
  PUSH = 'PUSH',
}

export enum NotificationPreferenceStatus {
  ENABLED = 'ENABLED',
  DISABLED = 'DISABLED',
  NOT_CONFIGURED = 'NOT_CONFIGURED',
}

export enum NotificationType {
  ELIGIBILITY_CHANGE = 'ELIGIBILITY_CHANGE',
  RECOMMENDATION_CHANGE = 'RECOMMENDATION_CHANGE',
  JOURNEY_PREREQUISITE_CHANGE = 'JOURNEY_PREREQUISITE_CHANGE',
  JOURNEY_DEADLINE_CHANGE = 'JOURNEY_DEADLINE_CHANGE',
  FACT_VERIFICATION_UPDATE = 'FACT_VERIFICATION_UPDATE',
  POLICY_CHANGE_ACTIVATION = 'POLICY_CHANGE_ACTIVATION',
}

export enum ActionType {
  REVIEW_ELIGIBILITY = 'REVIEW_ELIGIBILITY',
  REVIEW_RECOMMENDATION = 'REVIEW_RECOMMENDATION',
  UPLOAD_EVIDENCE = 'UPLOAD_EVIDENCE',
  COMPLETE_ONBOARDING = 'COMPLETE_ONBOARDING',
  COMPLETE_PREREQUISITE = 'COMPLETE_PREREQUISITE',
  ACKNOWLEDGE_POLICY_CHANGE = 'ACKNOWLEDGE_POLICY_CHANGE',
}

export enum SuppressionReason {
  COOLDOWN_ACTIVE = 'COOLDOWN_ACTIVE',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  QUIET_HOURS_ACTIVE = 'QUIET_HOURS_ACTIVE',
  CHANNEL_DISABLED = 'CHANNEL_DISABLED',
  IMMATERIAL_CHANGE = 'IMMATERIAL_CHANGE',
  SUPERSEDED = 'SUPERSEDED',
}

export enum FailureCategory {
  TRANSIENT = 'TRANSIENT',
  PERMANENT = 'PERMANENT',
  RATE_LIMITED = 'RATE_LIMITED',
  INVALID_DESTINATION = 'INVALID_DESTINATION',
  PROVIDER_UNAVAILABLE = 'PROVIDER_UNAVAILABLE',
  AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE',
  POLICY_REJECTED = 'POLICY_REJECTED',
}
