export enum OnboardingSessionStatus {
  STARTED = 'STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
  ABANDONED = 'ABANDONED',
}

export enum QuestionInputType {
  SINGLE_SELECT = 'SINGLE_SELECT',
  MULTI_SELECT = 'MULTI_SELECT',
  BOOLEAN = 'BOOLEAN',
  NUMBER = 'NUMBER',
  DECIMAL = 'DECIMAL',
  TEXT = 'TEXT',
  DATE = 'DATE',
  RANGE = 'RANGE',
  ADDRESS = 'ADDRESS',
  DOCUMENT_REQUIRED = 'DOCUMENT_REQUIRED',
  SELECT = 'SELECT',
  RADIO = 'RADIO',
  CHECKBOX = 'CHECKBOX',
  TEXTAREA = 'TEXTAREA',
}

export enum AnswerStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  VALIDATED = 'VALIDATED',
}
