/**
 * Centralized Domain Event Registry for GPIOS Platform
 * Organizes domain events cleanly across system boundaries with standardized version headers.
 */
export const DomainEventRegistry = {
  Authentication: {
    UserLoggedIn: 'user.logged_in',
    UserLoggedOut: 'user.logged_out',
    SessionCreated: 'session.created',
    SessionRevoked: 'session.revoked',
    PasswordChanged: 'password.changed',
    FailedLoginDetected: 'auth.failed_login',
  },
  Citizen: {
    ProfileCreated: 'citizen.profile_created',
    ProfileUpdated: 'citizen.profile_updated',
    FactCreated: 'citizen.fact_created',
    FactUpdated: 'citizen.fact_updated',
    FactConflictDetected: 'citizen.fact_conflict_detected',
    FactVerified: 'citizen.fact_verified',
    FactExpired: 'citizen.fact_expired',
    FactAdded: 'citizen.fact_added',
    FactDeleted: 'citizen.fact_deleted',
    ProfileVersionCreated: 'citizen.profile_version_created',
  },
  Onboarding: {
    Started: 'onboarding.started',
    QuestionAnswered: 'onboarding.question_answered',
    QuestionSkipped: 'onboarding.question_skipped',
    StepCompleted: 'onboarding.step_completed',
    Paused: 'onboarding.paused',
    Resumed: 'onboarding.resumed',
    Completed: 'onboarding.completed',
    SnapshotCreated: 'onboarding.snapshot_created',
    ImpactDetected: 'onboarding.impact_detected',
  },
  Knowledge: {
    SourceRegistered: 'knowledge.source_registered',
    SourceUpdated: 'knowledge.source_updated',
    DiscoveryStarted: 'knowledge.discovery_started',
    DocumentDownloaded: 'knowledge.document_downloaded',
    DocumentFingerprinted: 'knowledge.document_fingerprinted',
    DuplicateDetected: 'knowledge.document_duplicate_detected',
    DocumentProcessed: 'knowledge.document_processed',
    PolicyCreated: 'knowledge.policy_created',
    PolicyVersionCreated: 'knowledge.policy_version_created',
    ChunkCreated: 'knowledge.chunk_created',
    ChunkUpdated: 'knowledge.chunk_updated',
    ChunkDeleted: 'knowledge.chunk_deleted',
    MetadataExtracted: 'knowledge.metadata_extracted',
    IngestionCompleted: 'knowledge.ingestion_completed',
    IngestionFailed: 'knowledge.ingestion_failed',
  },
  Eligibility: {
    Started: 'eligibility.started',
    Completed: 'eligibility.completed',
    Failed: 'eligibility.failed',
    PolicyEvaluated: 'policy.evaluated',
    RuleExecuted: 'rule.executed',
    DecisionTraceCreated: 'decision.trace.created',
    SnapshotCreated: 'eligibility.snapshot.created',
    BenefitAnalysisCompleted: 'benefit.analysis.completed',
    OpportunityAnalysisCompleted: 'opportunity.analysis.completed',
    ExplanationGenerated: 'explanation.generated',
  },
  Policy: {
    PolicyRuleCreated: 'policy.rule_created',
  },
  Recommendation: {
    Generated: 'recommendation.generated',
    Updated: 'recommendation.updated',
    SnapshotCreated: 'recommendation.snapshot.created',
    PortfolioCreated: 'recommendation.portfolio.created',
    RankChanged: 'recommendation.rank.changed',
    ReadinessCompleted: 'recommendation.readiness.completed',
    UtilityCalculated: 'recommendation.utility.calculated',
    PreferenceUpdated: 'recommendation.preference.updated',
    ExplanationGenerated: 'recommendation.explanation.generated',
    DiffDetected: 'recommendation.diff.detected',
    AnalyticsGenerated: 'recommendation.analytics.generated',
    Expired: 'recommendation.expired',
  },
  Journey: {
    Created: 'journey.created',
    Updated: 'journey.updated',
    Started: 'journey.started',
    StepCompleted: 'journey.step.completed',
    StepBlocked: 'journey.step.blocked',
    ChecklistGenerated: 'journey.checklist.generated',
    DocumentRequired: 'journey.document.required',
    DeadlineUpdated: 'journey.deadline.updated',
    SnapshotCreated: 'journey.snapshot.created',
    TimelineUpdated: 'journey.timeline.updated',
    Completed: 'journey.completed',
    Archived: 'journey.archived',
  },
  Document: {
    Uploaded: 'document.uploaded',
    Classified: 'document.classified',
    QualityChecked: 'document.quality_checked',
    OcrCompleted: 'document.ocr.completed',
    FactsExtracted: 'document.facts.extracted',
    VerificationStarted: 'document.verification.started',
    Verified: 'document.verified',
    ConflictDetected: 'document.conflict.detected',
    Reconciled: 'document.reconciled',
    Expired: 'document.expired',
    Superseded: 'document.superseded',
  },
  Evidence: {
    Created: 'evidence.created',
    VersionCreated: 'evidence.version.created',
    VerificationCompleted: 'verification.completed',
    TrustCalculated: 'evidence.trust_calculated',
  },
  FactVerification: {
    Started: 'fact.verification_started',
    Completed: 'fact.verification_completed',
    Failed: 'fact.verification_failed',
    ConflictDetected: 'fact.conflict_detected',
    ConflictResolved: 'fact.conflict_resolved',
    CanonicalUpdated: 'fact.canonical_updated',
    Expired: 'fact.verification_expired',
    ManualReviewCreated: 'fact.manual_review_created',
    ManualReviewCompleted: 'fact.manual_review_completed',
    ReconciliationCompleted: 'fact.reconciliation_completed',
    ImpactDetected: 'fact.impact_detected',
    SnapshotCreated: 'fact.snapshot_created',
  },
  DecisionReEvaluation: {
    Requested: 'decision.reevaluation.requested',
    Planned: 'decision.reevaluation.planned',
    Started: 'decision.reevaluation.started',
    EligibilityCompleted: 'eligibility.reevaluation.completed',
    RecommendationCompleted: 'recommendation.reevaluation.completed',
    JourneyCompleted: 'journey.reevaluation.completed',
    StateChanged: 'decision.state_changed',
    StateUnchanged: 'decision.state_unchanged',
    Stale: 'decision.stale',
    Failed: 'decision.reevaluation_failed',
    PolicyChangeDetected: 'policy.change_detected',
    Completed: 'decision.reevaluation.completed',
  },
  Notification: {
    Created: 'notification.created',
    Rendered: 'notification.rendered',
    Queued: 'notification.queued',
    Dispatched: 'notification.dispatched',
    Delivered: 'notification.delivered',
    Failed: 'notification.failed',
    Read: 'notification.read',
    Superseded: 'notification.superseded',
    Suppressed: 'notification.suppressed',
  },
  ActionItem: {
    Created: 'action_item.created',
    Acknowledged: 'action_item.acknowledged',
    Completed: 'action_item.completed',
    Dismissed: 'action_item.dismissed',
    Expired: 'action_item.expired',
    Superseded: 'action_item.superseded',
  },
} as const;

export interface StandardDomainEventEnvelope<T = unknown> {
  eventId: string;
  eventName: string;
  eventVersion: string; // e.g. '1.0'
  aggregateId: string;
  aggregateVersion?: number;
  occurredOn: Date;
  occurredAt?: Date;
  correlationId?: string;
  causationId?: string;
  payload: T;
}
