/**
 * Centralized Dependency Injection Tokens for GPIOS Platform
 * Avoid string literal pollution across services and controllers.
 */
export const STORAGE_PROVIDER = Symbol('STORAGE_PROVIDER');
export const LLM_PROVIDER = Symbol('LLM_PROVIDER');
export const EMBEDDING_PROVIDER = Symbol('EMBEDDING_PROVIDER');
export const EVENT_PUBLISHER = Symbol('EVENT_PUBLISHER');
export const EVENT_SUBSCRIBER = Symbol('EVENT_SUBSCRIBER');
export const EVENT_DISPATCHER = Symbol('EVENT_DISPATCHER');
export const FEATURE_FLAG_PROVIDER = Symbol('FEATURE_FLAG_PROVIDER');
export const CLOCK_PROVIDER = Symbol('CLOCK_PROVIDER');

// IAM Infrastructure & Repository Tokens
export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const SESSION_REPOSITORY = Symbol('SESSION_REPOSITORY');
export const AUDIT_REPOSITORY = Symbol('AUDIT_REPOSITORY');
export const ROLE_REPOSITORY = Symbol('ROLE_REPOSITORY');
export const PASSWORD_HASHER = Symbol('PASSWORD_HASHER');
export const AUTH_SERVICE = Symbol('AUTH_SERVICE');

// Citizen Domain Tokens
export const CITIZEN_PROFILE_REPOSITORY = Symbol('CITIZEN_PROFILE_REPOSITORY');
export const CITIZEN_FACT_REPOSITORY = Symbol('CITIZEN_FACT_REPOSITORY');
export const CITIZEN_ATTRIBUTE_REGISTRY_REPOSITORY = Symbol('CITIZEN_ATTRIBUTE_REGISTRY_REPOSITORY');
export const PROFILE_VERSION_REPOSITORY = Symbol('PROFILE_VERSION_REPOSITORY');
export const EVIDENCE_REPOSITORY = Symbol('EVIDENCE_REPOSITORY');
export const ATTRIBUTE_VALIDATION_ENGINE = Symbol('ATTRIBUTE_VALIDATION_ENGINE');
export const COMPLETENESS_ENGINE = Symbol('COMPLETENESS_ENGINE');
export const SNAPSHOT_SERVICE = Symbol('SNAPSHOT_SERVICE');
export const CITIZEN_QUERY_SERVICE = Symbol('CITIZEN_QUERY_SERVICE');

// Onboarding Adaptive Discovery Engine Tokens
export const ONBOARDING_SESSION_REPOSITORY = Symbol('ONBOARDING_SESSION_REPOSITORY');
export const DISCOVERY_BLUEPRINT_REPOSITORY = Symbol('DISCOVERY_BLUEPRINT_REPOSITORY');
export const QUESTION_CATALOG_REPOSITORY = Symbol('QUESTION_CATALOG_REPOSITORY');
export const ANSWER_NORMALIZATION_ENGINE = Symbol('ANSWER_NORMALIZATION_ENGINE');
export const QUESTION_VISIBILITY_ENGINE = Symbol('QUESTION_VISIBILITY_ENGINE');
export const PROGRESS_CALCULATION_STRATEGY = Symbol('PROGRESS_CALCULATION_STRATEGY');
export const BLUEPRINT_MIGRATION_SERVICE = Symbol('BLUEPRINT_MIGRATION_SERVICE');
export const ONBOARDING_WORKFLOW_ENGINE = Symbol('ONBOARDING_WORKFLOW_ENGINE');
export const ONBOARDING_SESSION_SERVICE = Symbol('ONBOARDING_SESSION_SERVICE');
export const ONBOARDING_ANALYTICS_SERVICE = Symbol('ONBOARDING_ANALYTICS_SERVICE');

// Knowledge Acquisition & Policy Intelligence Tokens
export const KNOWLEDGE_SOURCE_REPOSITORY = Symbol('KNOWLEDGE_SOURCE_REPOSITORY');
export const POLICY_DOCUMENT_REPOSITORY = Symbol('POLICY_DOCUMENT_REPOSITORY');
export const POLICY_VERSION_REPOSITORY = Symbol('POLICY_VERSION_REPOSITORY');
export const POLICY_CHUNK_REPOSITORY = Symbol('POLICY_CHUNK_REPOSITORY');
export const INGESTION_JOB_REPOSITORY = Symbol('INGESTION_JOB_REPOSITORY');
export const FINGERPRINT_REPOSITORY = Symbol('FINGERPRINT_REPOSITORY');
export const POLICY_FINGERPRINT_SERVICE = Symbol('POLICY_FINGERPRINT_SERVICE');
export const REFRESH_SCHEDULER_SERVICE = Symbol('REFRESH_SCHEDULER_SERVICE');
export const DOCUMENT_PROCESSING_PIPELINE = Symbol('DOCUMENT_PROCESSING_PIPELINE');
export const METADATA_EXTRACTION_SERVICE = Symbol('METADATA_EXTRACTION_SERVICE');
export const POLICY_NORMALIZATION_SERVICE = Symbol('POLICY_NORMALIZATION_SERVICE');
export const CHUNK_GENERATION_SERVICE = Symbol('CHUNK_GENERATION_SERVICE');
export const KNOWLEDGE_QUALITY_SERVICE = Symbol('KNOWLEDGE_QUALITY_SERVICE');
export const KNOWLEDGE_QUERY_SERVICE = Symbol('KNOWLEDGE_QUERY_SERVICE');
export const KNOWLEDGE_STATISTICS_SERVICE = Symbol('KNOWLEDGE_STATISTICS_SERVICE');
export const KNOWLEDGE_SOURCE_SERVICE = Symbol('KNOWLEDGE_SOURCE_SERVICE');
export const KNOWLEDGE_INGESTION_SERVICE = Symbol('KNOWLEDGE_INGESTION_SERVICE');
export const PARSER_REGISTRY = Symbol('PARSER_REGISTRY');
export const CONNECTOR_FACTORY = Symbol('CONNECTOR_FACTORY');

// Eligibility Intelligence Engine & Decision Trace Platform Tokens
export const POLICY_RULE_REPOSITORY = Symbol('POLICY_RULE_REPOSITORY');
export const DECISION_TRACE_REPOSITORY = Symbol('DECISION_TRACE_REPOSITORY');
export const ELIGIBILITY_SNAPSHOT_REPOSITORY = Symbol('ELIGIBILITY_SNAPSHOT_REPOSITORY');
export const OPPORTUNITY_REPOSITORY = Symbol('OPPORTUNITY_REPOSITORY');
export const BENEFIT_REPOSITORY = Symbol('BENEFIT_REPOSITORY');
export const POLICY_VALIDATION_SERVICE = Symbol('POLICY_VALIDATION_SERVICE');
export const RULE_ENGINE_SERVICE = Symbol('RULE_ENGINE_SERVICE');
export const COMPILED_RULE_CACHE_SERVICE = Symbol('COMPILED_RULE_CACHE_SERVICE');
export const EVALUATION_EXECUTION_PLANNER = Symbol('EVALUATION_EXECUTION_PLANNER');
export const FACT_USAGE_INDEX_SERVICE = Symbol('FACT_USAGE_INDEX_SERVICE');
export const DEPENDENCY_GRAPH_SERVICE = Symbol('DEPENDENCY_GRAPH_SERVICE');
export const EVALUATION_GRAPH_SERVICE = Symbol('EVALUATION_GRAPH_SERVICE');
export const TRACE_STORE_SERVICE = Symbol('TRACE_STORE_SERVICE');
export const SNAPSHOT_SERVICE_ELIGIBILITY = Symbol('SNAPSHOT_SERVICE_ELIGIBILITY');
export const CONTEXT_ENGINE_SERVICE = Symbol('CONTEXT_ENGINE_SERVICE');
export const BENEFIT_INTELLIGENCE_SERVICE = Symbol('BENEFIT_INTELLIGENCE_SERVICE');
export const OPPORTUNITY_INTELLIGENCE_SERVICE = Symbol('OPPORTUNITY_INTELLIGENCE_SERVICE');
export const EXPLAINABILITY_SERVICE = Symbol('EXPLAINABILITY_SERVICE');
export const DECISION_REPLAY_SERVICE = Symbol('DECISION_REPLAY_SERVICE');
export const EVALUATION_METRICS_SERVICE = Symbol('EVALUATION_METRICS_SERVICE');
export const INCREMENTAL_EVALUATION_SERVICE = Symbol('INCREMENTAL_EVALUATION_SERVICE');
export const ELIGIBILITY_EVALUATION_ORCHESTRATOR = Symbol('ELIGIBILITY_EVALUATION_ORCHESTRATOR');
export const ELIGIBILITY_QUERY_SERVICE = Symbol('ELIGIBILITY_QUERY_SERVICE');

// Recommendation Intelligence & Personalized Opportunity Platform Tokens
export const RECOMMENDATION_REPOSITORY = Symbol('RECOMMENDATION_REPOSITORY');
export const RECOMMENDATION_PORTFOLIO_REPOSITORY = Symbol('RECOMMENDATION_PORTFOLIO_REPOSITORY');
export const RECOMMENDATION_SNAPSHOT_REPOSITORY = Symbol('RECOMMENDATION_SNAPSHOT_REPOSITORY');
export const RECOMMENDATION_FEEDBACK_REPOSITORY = Symbol('RECOMMENDATION_FEEDBACK_REPOSITORY');
export const RECOMMENDATION_STRATEGY_FACTORY = Symbol('RECOMMENDATION_STRATEGY_FACTORY');
export const UTILITY_RECOMMENDATION_STRATEGY = Symbol('UTILITY_RECOMMENDATION_STRATEGY');
export const RECOMMENDATION_UTILITY_SERVICE = Symbol('RECOMMENDATION_UTILITY_SERVICE');
export const APPLICATION_READINESS_SERVICE = Symbol('APPLICATION_READINESS_SERVICE');
export const RECOMMENDATION_DEPENDENCY_SERVICE = Symbol('RECOMMENDATION_DEPENDENCY_SERVICE');
export const RECOMMENDATION_PORTFOLIO_OPTIMIZER = Symbol('RECOMMENDATION_PORTFOLIO_OPTIMIZER');
export const RECOMMENDATION_RANKING_SERVICE = Symbol('RECOMMENDATION_RANKING_SERVICE');
export const RECOMMENDATION_EXPLAINABILITY_SERVICE = Symbol('RECOMMENDATION_EXPLAINABILITY_SERVICE');
export const RECOMMENDATION_SNAPSHOT_SERVICE = Symbol('RECOMMENDATION_SNAPSHOT_SERVICE');
export const RECOMMENDATION_REPLAY_SERVICE = Symbol('RECOMMENDATION_REPLAY_SERVICE');
export const RECOMMENDATION_DIFF_SERVICE = Symbol('RECOMMENDATION_DIFF_SERVICE');
export const RECOMMENDATION_HISTORY_SERVICE = Symbol('RECOMMENDATION_HISTORY_SERVICE');
export const RECOMMENDATION_LIFECYCLE_SERVICE = Symbol('RECOMMENDATION_LIFECYCLE_SERVICE');
export const RECOMMENDATION_PREFERENCE_SERVICE = Symbol('RECOMMENDATION_PREFERENCE_SERVICE');
export const RECOMMENDATION_FEEDBACK_SERVICE = Symbol('RECOMMENDATION_FEEDBACK_SERVICE');
export const RECOMMENDATION_ANALYTICS_SERVICE = Symbol('RECOMMENDATION_ANALYTICS_SERVICE');
export const RECOMMENDATION_GENERATION_SERVICE = Symbol('RECOMMENDATION_GENERATION_SERVICE');
export const RECOMMENDATION_QUERY_SERVICE = Symbol('RECOMMENDATION_QUERY_SERVICE');

// Application Journey & Action Planning Engine Tokens
export const APPLICATION_JOURNEY_REPOSITORY = Symbol('APPLICATION_JOURNEY_REPOSITORY');
export const JOURNEY_BLUEPRINT_REPOSITORY = Symbol('JOURNEY_BLUEPRINT_REPOSITORY');
export const JOURNEY_SNAPSHOT_REPOSITORY = Symbol('JOURNEY_SNAPSHOT_REPOSITORY');
export const JOURNEY_BLUEPRINT_SERVICE = Symbol('JOURNEY_BLUEPRINT_SERVICE');
export const JOURNEY_CONSTRAINT_ENGINE = Symbol('JOURNEY_CONSTRAINT_ENGINE');
export const JOURNEY_DEPENDENCY_GRAPH_SERVICE = Symbol('JOURNEY_DEPENDENCY_GRAPH_SERVICE');
export const JOURNEY_PLANNER_SERVICE = Symbol('JOURNEY_PLANNER_SERVICE');
export const CHECKLIST_GENERATION_SERVICE = Symbol('CHECKLIST_GENERATION_SERVICE');
export const DOCUMENT_REQUIREMENT_SERVICE = Symbol('DOCUMENT_REQUIREMENT_SERVICE');
export const JOURNEY_READINESS_SERVICE = Symbol('JOURNEY_READINESS_SERVICE');
export const DEADLINE_INTELLIGENCE_SERVICE = Symbol('DEADLINE_INTELLIGENCE_SERVICE');
export const ACTION_PLANNING_SERVICE = Symbol('ACTION_PLANNING_SERVICE');
export const JOURNEY_PROGRESS_SERVICE = Symbol('JOURNEY_PROGRESS_SERVICE');
export const JOURNEY_SNAPSHOT_SERVICE = Symbol('JOURNEY_SNAPSHOT_SERVICE');
export const JOURNEY_REPLAY_SERVICE = Symbol('JOURNEY_REPLAY_SERVICE');
export const JOURNEY_EVENT_REPLAY_SERVICE = Symbol('JOURNEY_EVENT_REPLAY_SERVICE');
export const JOURNEY_DIFFERENCE_SERVICE = Symbol('JOURNEY_DIFFERENCE_SERVICE');
export const JOURNEY_TIMELINE_SERVICE = Symbol('JOURNEY_TIMELINE_SERVICE');
export const JOURNEY_ANALYTICS_SERVICE = Symbol('JOURNEY_ANALYTICS_SERVICE');
export const APPLICATION_JOURNEY_ORCHESTRATOR = Symbol('APPLICATION_JOURNEY_ORCHESTRATOR');
export const JOURNEY_QUERY_SERVICE = Symbol('JOURNEY_QUERY_SERVICE');

// Document Intelligence, Evidence Management & Verification Platform Tokens
export const DOCUMENT_REPOSITORY = Symbol('DOCUMENT_REPOSITORY');
export const DOCUMENT_EVIDENCE_REPOSITORY = Symbol('DOCUMENT_EVIDENCE_REPOSITORY');
export const VERIFICATION_REPOSITORY = Symbol('VERIFICATION_REPOSITORY');
export const CONFLICT_REPOSITORY = Symbol('CONFLICT_REPOSITORY');
export const DOCUMENT_STORAGE_SERVICE = Symbol('DOCUMENT_STORAGE_SERVICE');
export const DOCUMENT_LIFECYCLE_SERVICE = Symbol('DOCUMENT_LIFECYCLE_SERVICE');
export const DOCUMENT_CLASSIFICATION_SERVICE = Symbol('DOCUMENT_CLASSIFICATION_SERVICE');
export const DOCUMENT_QUALITY_ASSESSMENT_SERVICE = Symbol('DOCUMENT_QUALITY_ASSESSMENT_SERVICE');
export const OCR_ORCHESTRATOR_SERVICE = Symbol('OCR_ORCHESTRATOR_SERVICE');
export const OCR_EXTRACTION_SERVICE = Symbol('OCR_EXTRACTION_SERVICE');
export const EVIDENCE_GENERATION_SERVICE = Symbol('EVIDENCE_GENERATION_SERVICE');
export const EVIDENCE_VERSION_SERVICE = Symbol('EVIDENCE_VERSION_SERVICE');
export const EVIDENCE_TRUST_SCORE_SERVICE = Symbol('EVIDENCE_TRUST_SCORE_SERVICE');
export const EVIDENCE_GRAPH_SERVICE = Symbol('EVIDENCE_GRAPH_SERVICE');
export const VERIFICATION_WORKFLOW_SERVICE = Symbol('VERIFICATION_WORKFLOW_SERVICE');
export const VERIFICATION_POLICY_SERVICE = Symbol('VERIFICATION_POLICY_SERVICE');
export const CONFIDENCE_CALCULATION_SERVICE = Symbol('CONFIDENCE_CALCULATION_SERVICE');
export const CONFLICT_DETECTION_SERVICE = Symbol('CONFLICT_DETECTION_SERVICE');
export const FACT_RECONCILIATION_SERVICE = Symbol('FACT_RECONCILIATION_SERVICE');
export const DOCUMENT_DEDUPLICATION_SERVICE = Symbol('DOCUMENT_DEDUPLICATION_SERVICE');
export const EXPIRY_INTELLIGENCE_SERVICE = Symbol('EXPIRY_INTELLIGENCE_SERVICE');
export const DOCUMENT_ANALYTICS_SERVICE = Symbol('DOCUMENT_ANALYTICS_SERVICE');
export const DOCUMENT_REPLAY_SERVICE = Symbol('DOCUMENT_REPLAY_SERVICE');
export const DOCUMENT_ORCHESTRATOR = Symbol('DOCUMENT_ORCHESTRATOR');
export const DOCUMENT_QUERY_SERVICE = Symbol('DOCUMENT_QUERY_SERVICE');

// Citizen Knowledge Profile & Adaptive Onboarding Platform Tokens (Sprint 9)
export const CITIZEN_KNOWLEDGE_PROFILE_REPOSITORY = Symbol('CITIZEN_KNOWLEDGE_PROFILE_REPOSITORY');
export const ONBOARDING_QUESTION_REPOSITORY = Symbol('ONBOARDING_QUESTION_REPOSITORY');
export const CITIZEN_KNOWLEDGE_PROFILE_SERVICE = Symbol('CITIZEN_KNOWLEDGE_PROFILE_SERVICE');
export const FACT_SOURCE_PRECEDENCE_POLICY = Symbol('FACT_SOURCE_PRECEDENCE_POLICY');
export const FACT_VERSION_SERVICE = Symbol('FACT_VERSION_SERVICE');
export const FACT_FRESHNESS_ENGINE_SERVICE = Symbol('FACT_FRESHNESS_ENGINE_SERVICE');
export const PROFILE_COMPLETENESS_ENGINE_SERVICE = Symbol('PROFILE_COMPLETENESS_ENGINE_SERVICE');
export const ADAPTIVE_QUESTION_ENGINE_SERVICE = Symbol('ADAPTIVE_QUESTION_ENGINE_SERVICE');
export const QUESTION_DEPENDENCY_ENGINE_SERVICE = Symbol('QUESTION_DEPENDENCY_ENGINE_SERVICE');
export const QUESTION_PRIORITIZATION_ENGINE_SERVICE = Symbol('QUESTION_PRIORITIZATION_ENGINE_SERVICE');
export const DOCUMENT_AWARE_QUESTION_ENGINE_SERVICE = Symbol('DOCUMENT_AWARE_QUESTION_ENGINE_SERVICE');
export const ANSWER_PROCESSING_ENGINE_SERVICE = Symbol('ANSWER_PROCESSING_ENGINE_SERVICE');
export const QUESTION_EXPLAINABILITY_SERVICE = Symbol('QUESTION_EXPLAINABILITY_SERVICE');
export const PROFILE_SNAPSHOT_REPLAY_SERVICE = Symbol('PROFILE_SNAPSHOT_REPLAY_SERVICE');
export const CHANGE_IMPACT_ENGINE_SERVICE = Symbol('CHANGE_IMPACT_ENGINE_SERVICE');
export const ONBOARDING_SESSION_ENGINE_SERVICE = Symbol('ONBOARDING_SESSION_ENGINE_SERVICE');

// Enterprise Fact Verification, Evidence Reconciliation & Citizen Truth Engine Tokens (Sprint 10)
export const FACT_VERIFICATION_REPOSITORY = Symbol('FACT_VERIFICATION_REPOSITORY');
export const CANONICAL_FACT_RESOLUTION_SERVICE = Symbol('CANONICAL_FACT_RESOLUTION_SERVICE');
export const FACT_CONFLICT_ENGINE_SERVICE = Symbol('FACT_CONFLICT_ENGINE_SERVICE');
export const FACT_VERIFICATION_POLICY_ENGINE_SERVICE = Symbol('FACT_VERIFICATION_POLICY_ENGINE_SERVICE');
export const EVIDENCE_CHAIN_VALIDATION_SERVICE = Symbol('EVIDENCE_CHAIN_VALIDATION_SERVICE');
export const FACT_FRESHNESS_REVALIDATION_SERVICE = Symbol('FACT_FRESHNESS_REVALIDATION_SERVICE');
export const FACT_RECONCILIATION_WORKFLOW_SERVICE = Symbol('FACT_RECONCILIATION_WORKFLOW_SERVICE');
export const FACT_VERIFICATION_REVIEW_SERVICE = Symbol('FACT_VERIFICATION_REVIEW_SERVICE');
export const FACT_VERIFICATION_REPLAY_SERVICE = Symbol('FACT_VERIFICATION_REPLAY_SERVICE');
export const FACT_VERIFICATION_IMPACT_ENGINE_SERVICE = Symbol('FACT_VERIFICATION_IMPACT_ENGINE_SERVICE');
export const FACT_VERIFICATION_ORCHESTRATOR = Symbol('FACT_VERIFICATION_ORCHESTRATOR');

// Enterprise Continuous Decision Re-evaluation, Impact Propagation & Policy Change Intelligence Platform Tokens (Sprint 11)
export const DECISION_RE_EVALUATION_REPOSITORY = Symbol('DECISION_RE_EVALUATION_REPOSITORY');
export const CHANGE_DETECTION_SERVICE = Symbol('CHANGE_DETECTION_SERVICE');
export const DECISION_IMPACT_ANALYSIS_SERVICE = Symbol('DECISION_IMPACT_ANALYSIS_SERVICE');
export const DECISION_DEPENDENCY_RESOLUTION_SERVICE = Symbol('DECISION_DEPENDENCY_RESOLUTION_SERVICE');
export const RE_EVALUATION_PLANNER_SERVICE = Symbol('RE_EVALUATION_PLANNER_SERVICE');
export const RE_EVALUATION_EXECUTOR_SERVICE = Symbol('RE_EVALUATION_EXECUTOR_SERVICE');
export const ELIGIBILITY_RE_EVALUATION_SERVICE = Symbol('ELIGIBILITY_RE_EVALUATION_SERVICE');
export const RECOMMENDATION_RE_EVALUATION_SERVICE = Symbol('RECOMMENDATION_RE_EVALUATION_SERVICE');
export const JOURNEY_RE_EVALUATION_SERVICE = Symbol('JOURNEY_RE_EVALUATION_SERVICE');
export const DECISION_DIFF_SERVICE = Symbol('DECISION_DIFF_SERVICE');
export const STALE_STATE_SERVICE = Symbol('STALE_STATE_SERVICE');
export const POLICY_CHANGE_INTELLIGENCE_SERVICE = Symbol('POLICY_CHANGE_INTELLIGENCE_SERVICE');
export const RE_EVALUATION_REPLAY_SERVICE = Symbol('RE_EVALUATION_REPLAY_SERVICE');
export const RE_EVALUATION_ANALYTICS_SERVICE = Symbol('RE_EVALUATION_ANALYTICS_SERVICE');
export const DECISION_RE_EVALUATION_ORCHESTRATOR = Symbol('DECISION_RE_EVALUATION_ORCHESTRATOR');

// Enterprise Decision Change Notification, Action Center & Communication Orchestration Platform Tokens (Sprint 12)
export const NOTIFICATION_REPOSITORY = Symbol('NOTIFICATION_REPOSITORY');
export const NOTIFICATION_INGESTION_SERVICE = Symbol('NOTIFICATION_INGESTION_SERVICE');
export const NOTIFICATION_POLICY_SERVICE = Symbol('NOTIFICATION_POLICY_SERVICE');
export const CHANNEL_RESOLUTION_SERVICE = Symbol('CHANNEL_RESOLUTION_SERVICE');
export const NOTIFICATION_RENDERER_SERVICE = Symbol('NOTIFICATION_RENDERER_SERVICE');
export const NOTIFICATION_SUPERSESSION_SERVICE = Symbol('NOTIFICATION_SUPERSESSION_SERVICE');
export const ACTION_CENTER_SERVICE = Symbol('ACTION_CENTER_SERVICE');
export const NOTIFICATION_OUTBOX_SERVICE = Symbol('NOTIFICATION_OUTBOX_SERVICE');
export const NOTIFICATION_REPLAY_SERVICE = Symbol('NOTIFICATION_REPLAY_SERVICE');
export const NOTIFICATION_ANALYTICS_SERVICE = Symbol('NOTIFICATION_ANALYTICS_SERVICE');
export const NOTIFICATION_ORCHESTRATOR_SERVICE = Symbol('NOTIFICATION_ORCHESTRATOR_SERVICE');

export const IN_APP_CHANNEL_ADAPTER = Symbol('IN_APP_CHANNEL_ADAPTER');
export const EMAIL_CHANNEL_ADAPTER = Symbol('EMAIL_CHANNEL_ADAPTER');
export const SMS_CHANNEL_ADAPTER = Symbol('SMS_CHANNEL_ADAPTER');
export const PUSH_CHANNEL_ADAPTER = Symbol('PUSH_CHANNEL_ADAPTER');




